version: '2'
services:
  # Rabbit is our main message queue
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  # Celery beat
  scheduler:
    image: collins
    build: .
    command: python scheduler.py
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
      - SCHEDULER_API=http://api:8000/api/v1/schedulers/
      - DJANGO_SETTINGS_MODULE="collins.settings.prod"
    links:
      - rabbit
      - api
    volumes:
      - ./:/code
    depends_on:
      - rabbit
  # Django based api/admin site
  api:
    image: collins
    build: .
    command: /code/start_api.sh
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
    links:
      - rabbit
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - rabbit

  # flower
  monitor:
    image: collins-monitor
    build: ./monitor
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
    build: ./monitor
    links:
      - rabbit
    ports:
      - 5555:5555
    depends_on:
      - rabbit


  # remote client
  site_1:
    image: collins-worker
    build: ./clients/client/
    environment:
      - SITE_NAME=SITE_1
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
      - RESULTS_API=http://api:8000/api/v1/results/
    links:
      - rabbit
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbit
      - api

  # remote client
  site_2:
    image: collins-worker
    build: ./clients/client/
    environment:
      - SITE_NAME=SITE_2
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
      - RESULTS_API=http://api:8000/api/v1/results/
    links:
      - rabbit
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbit
      - api