# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='user',
        ),
        migrations.AddField(
            model_name='gateway',
            name='authorized_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
