# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0002_auto_20170601_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
