# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20160315_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyport',
            name='proxyport',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='proxyport',
            unique_together=set([('cloudserver', 'proxyport')]),
        ),
    ]
