# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20170601_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='authorized_users',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
