# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('connect', '0008_auto_20170608_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
