# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_gateway_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tunnel',
            options={'permissions': (('view_tunnel', 'View tunnel'),)},
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='connect.Gateway'),
        ),
    ]
