# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from html_field.db.models.fields import HTMLField
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('json', jsonfield.fields.JSONField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('type', models.CharField(default='DockerJob', max_length=25)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jobId', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('json', jsonfield.fields.JSONField(max_length=512, null=True)),
                ('pluginHTMLResponse', HTMLField(null=True)),
                ('pluginRawResponse', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('restart', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DockerJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Job')),
                ('image', models.CharField(max_length=128)),
            ],
            bases=('api.job',),
        ),
        migrations.AddField(
            model_name='job',
            name='environment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together=set([('name', 'description', 'json')]),
        ),
        migrations.AddField(
            model_name='result',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.DockerJob'),
        ),
    ]
