# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=70)),
                ('cardimageurl', models.URLField()),
                ('dockerimage', models.CharField(max_length=100)),
            ],
        ),
    ]
