# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_result_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='added',
            new_name='created',
        ),
    ]
