# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170428_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-created']},
        ),
    ]
