# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170509_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='restart',
            field=models.BooleanField(default=True),
        ),
    ]
