# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_job_last_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
