# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170511_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
