# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170511_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(default='descr', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='environment',
            name='json',
            field=jsonfield.fields.JSONField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
    ]
