# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data33(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, destination=None, type=None, ports=None, processed=None, results=None):
        """
        Data33 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'destination': 'str',
            'type': 'str',
            'ports': 'str',
            'processed': 'bool',
            'results': 'str'
        }

        self.attribute_map = {
            'destination': 'destination',
            'type': 'type',
            'ports': 'ports',
            'processed': 'processed',
            'results': 'results'
        }

        self._destination = destination
        self._type = type
        self._ports = ports
        self._processed = processed
        self._results = results

    @property
    def destination(self):
        """
        Gets the destination of this Data33.
        

        :return: The destination of this Data33.
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """
        Sets the destination of this Data33.
        

        :param destination: The destination of this Data33.
        :type: str
        """

        self._destination = destination

    @property
    def type(self):
        """
        Gets the type of this Data33.
        

        :return: The type of this Data33.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Data33.
        

        :param type: The type of this Data33.
        :type: str
        """

        self._type = type

    @property
    def ports(self):
        """
        Gets the ports of this Data33.
        

        :return: The ports of this Data33.
        :rtype: str
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """
        Sets the ports of this Data33.
        

        :param ports: The ports of this Data33.
        :type: str
        """

        self._ports = ports

    @property
    def processed(self):
        """
        Gets the processed of this Data33.
        

        :return: The processed of this Data33.
        :rtype: bool
        """
        return self._processed

    @processed.setter
    def processed(self, processed):
        """
        Sets the processed of this Data33.
        

        :param processed: The processed of this Data33.
        :type: bool
        """

        self._processed = processed

    @property
    def results(self):
        """
        Gets the results of this Data33.
        

        :return: The results of this Data33.
        :rtype: str
        """
        return self._results

    @results.setter
    def results(self, results):
        """
        Sets the results of this Data33.
        

        :param results: The results of this Data33.
        :type: str
        """

        self._results = results

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data33):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
