# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data6(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, queue=None, name=None, image=None, interval=None, enabled=None, environment=None, type=None):
        """
        Data6 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'queue': 'str',
            'name': 'str',
            'image': 'str',
            'interval': 'object',
            'enabled': 'bool',
            'environment': 'object',
            'type': 'str'
        }

        self.attribute_map = {
            'queue': 'queue',
            'name': 'name',
            'image': 'image',
            'interval': 'interval',
            'enabled': 'enabled',
            'environment': 'environment',
            'type': 'type'
        }

        self._queue = queue
        self._name = name
        self._image = image
        self._interval = interval
        self._enabled = enabled
        self._environment = environment
        self._type = type

    @property
    def queue(self):
        """
        Gets the queue of this Data6.
        Queue defined in CELERY_TASK_QUEUES

        :return: The queue of this Data6.
        :rtype: str
        """
        return self._queue

    @queue.setter
    def queue(self, queue):
        """
        Sets the queue of this Data6.
        Queue defined in CELERY_TASK_QUEUES

        :param queue: The queue of this Data6.
        :type: str
        """

        self._queue = queue

    @property
    def name(self):
        """
        Gets the name of this Data6.
        Useful description

        :return: The name of this Data6.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Data6.
        Useful description

        :param name: The name of this Data6.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def image(self):
        """
        Gets the image of this Data6.
        

        :return: The image of this Data6.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """
        Sets the image of this Data6.
        

        :param image: The image of this Data6.
        :type: str
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")

        self._image = image

    @property
    def interval(self):
        """
        Gets the interval of this Data6.
        

        :return: The interval of this Data6.
        :rtype: object
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """
        Sets the interval of this Data6.
        

        :param interval: The interval of this Data6.
        :type: object
        """
        if interval is None:
            raise ValueError("Invalid value for `interval`, must not be `None`")

        self._interval = interval

    @property
    def enabled(self):
        """
        Gets the enabled of this Data6.
        

        :return: The enabled of this Data6.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this Data6.
        

        :param enabled: The enabled of this Data6.
        :type: bool
        """

        self._enabled = enabled

    @property
    def environment(self):
        """
        Gets the environment of this Data6.
        

        :return: The environment of this Data6.
        :rtype: object
        """
        return self._environment

    @environment.setter
    def environment(self, environment):
        """
        Sets the environment of this Data6.
        

        :param environment: The environment of this Data6.
        :type: object
        """

        self._environment = environment

    @property
    def type(self):
        """
        Gets the type of this Data6.
        

        :return: The type of this Data6.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Data6.
        

        :param type: The type of this Data6.
        :type: str
        """

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data6):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
