# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Data20(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, remoteport=None, remotehost=None, sourceip=None, timeout=None):
        """
        Data20 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'remoteport': 'int',
            'remotehost': 'str',
            'sourceip': 'str',
            'timeout': 'int'
        }

        self.attribute_map = {
            'remoteport': 'remoteport',
            'remotehost': 'remotehost',
            'sourceip': 'sourceip',
            'timeout': 'timeout'
        }

        self._remoteport = remoteport
        self._remotehost = remotehost
        self._sourceip = sourceip
        self._timeout = timeout

    @property
    def remoteport(self):
        """
        Gets the remoteport of this Data20.
        

        :return: The remoteport of this Data20.
        :rtype: int
        """
        return self._remoteport

    @remoteport.setter
    def remoteport(self, remoteport):
        """
        Sets the remoteport of this Data20.
        

        :param remoteport: The remoteport of this Data20.
        :type: int
        """

        self._remoteport = remoteport

    @property
    def remotehost(self):
        """
        Gets the remotehost of this Data20.
        

        :return: The remotehost of this Data20.
        :rtype: str
        """
        return self._remotehost

    @remotehost.setter
    def remotehost(self, remotehost):
        """
        Sets the remotehost of this Data20.
        

        :param remotehost: The remotehost of this Data20.
        :type: str
        """

        self._remotehost = remotehost

    @property
    def sourceip(self):
        """
        Gets the sourceip of this Data20.
        

        :return: The sourceip of this Data20.
        :rtype: str
        """
        return self._sourceip

    @sourceip.setter
    def sourceip(self, sourceip):
        """
        Sets the sourceip of this Data20.
        

        :param sourceip: The sourceip of this Data20.
        :type: str
        """

        self._sourceip = sourceip

    @property
    def timeout(self):
        """
        Gets the timeout of this Data20.
        

        :return: The timeout of this Data20.
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """
        Sets the timeout of this Data20.
        

        :param timeout: The timeout of this Data20.
        :type: int
        """

        self._timeout = timeout

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Data20):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
