# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.inventory_api import InventoryApi


class TestInventoryApi(unittest.TestCase):
    """ InventoryApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.inventory_api.InventoryApi()

    def tearDown(self):
        pass

    def test_devices_create(self):
        """
        Test case for devices_create

        create a device
        """
        pass

    def test_devices_delete(self):
        """
        Test case for devices_delete

        delete a device
        """
        pass

    def test_devices_list(self):
        """
        Test case for devices_list

        list all devices
        """
        pass

    def test_devices_partial_update(self):
        """
        Test case for devices_partial_update

        update fields on a device
        """
        pass

    def test_devices_read(self):
        """
        Test case for devices_read

        get a device
        """
        pass

    def test_devices_update(self):
        """
        Test case for devices_update

        update a device
        """
        pass

    def test_systems_create(self):
        """
        Test case for systems_create

        create a system
        """
        pass

    def test_systems_delete(self):
        """
        Test case for systems_delete

        delete a system
        """
        pass

    def test_systems_list(self):
        """
        Test case for systems_list

        list all systems
        """
        pass

    def test_systems_partial_update(self):
        """
        Test case for systems_partial_update

        update fields on a system
        """
        pass

    def test_systems_read(self):
        """
        Test case for systems_read

        get a system
        """
        pass

    def test_systems_update(self):
        """
        Test case for systems_update

        update a system
        """
        pass


if __name__ == '__main__':
    unittest.main()
