# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.connect_api import ConnectApi


class TestConnectApi(unittest.TestCase):
    """ ConnectApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.connect_api.ConnectApi()

    def tearDown(self):
        pass

    def test_createtunnel_create(self):
        """
        Test case for createtunnel_create

        create a tunnel
        """
        pass

    def test_createtunnel_delete(self):
        """
        Test case for createtunnel_delete

        delete a tunnel
        """
        pass

    def test_createtunnel_list(self):
        """
        Test case for createtunnel_list

        
        """
        pass

    def test_createtunnel_partial_update(self):
        """
        Test case for createtunnel_partial_update

        update fields on a tunnel
        """
        pass

    def test_createtunnel_read(self):
        """
        Test case for createtunnel_read

        
        """
        pass

    def test_createtunnel_update(self):
        """
        Test case for createtunnel_update

        update a tunnel
        """
        pass

    def test_gateway_create(self):
        """
        Test case for gateway_create

        create a gateway
        """
        pass

    def test_gateway_delete(self):
        """
        Test case for gateway_delete

        delete a gateway
        """
        pass

    def test_gateway_list(self):
        """
        Test case for gateway_list

        list all gateways
        """
        pass

    def test_gateway_partial_update(self):
        """
        Test case for gateway_partial_update

        update fields on a gateway
        """
        pass

    def test_gateway_read(self):
        """
        Test case for gateway_read

        get a gateway
        """
        pass

    def test_gateway_update(self):
        """
        Test case for gateway_update

        update a Gateway
        """
        pass

    def test_gateways_create(self):
        """
        Test case for gateways_create

        create a gateway
        """
        pass

    def test_gateways_delete(self):
        """
        Test case for gateways_delete

        delete a gateway
        """
        pass

    def test_gateways_list(self):
        """
        Test case for gateways_list

        list all gateways
        """
        pass

    def test_gateways_partial_update(self):
        """
        Test case for gateways_partial_update

        update fields on a gateway
        """
        pass

    def test_gateways_read(self):
        """
        Test case for gateways_read

        get a gateway
        """
        pass

    def test_gateways_update(self):
        """
        Test case for gateways_update

        update a Gateway
        """
        pass

    def test_tunnel_create(self):
        """
        Test case for tunnel_create

        create a tunnel
        """
        pass

    def test_tunnel_delete(self):
        """
        Test case for tunnel_delete

        delete a tunnel
        """
        pass

    def test_tunnel_list(self):
        """
        Test case for tunnel_list

        list all tunnels
        """
        pass

    def test_tunnel_partial_update(self):
        """
        Test case for tunnel_partial_update

        update fields on a tunnel
        """
        pass

    def test_tunnel_read(self):
        """
        Test case for tunnel_read

        get a tunnel
        """
        pass

    def test_tunnel_update(self):
        """
        Test case for tunnel_update

        update a tunnel
        """
        pass

    def test_tunnels_create(self):
        """
        Test case for tunnels_create

        create a tunnel
        """
        pass

    def test_tunnels_delete(self):
        """
        Test case for tunnels_delete

        delete a tunnel
        """
        pass

    def test_tunnels_list(self):
        """
        Test case for tunnels_list

        list all tunnels
        """
        pass

    def test_tunnels_partial_update(self):
        """
        Test case for tunnels_partial_update

        update fields on a tunnel
        """
        pass

    def test_tunnels_read(self):
        """
        Test case for tunnels_read

        get a tunnel
        """
        pass

    def test_tunnels_update(self):
        """
        Test case for tunnels_update

        update a tunnel
        """
        pass


if __name__ == '__main__':
    unittest.main()
