# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.discover_api import DiscoverApi


class TestDiscoverApi(unittest.TestCase):
    """ DiscoverApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.discover_api.DiscoverApi()

    def tearDown(self):
        pass

    def test_scans_create(self):
        """
        Test case for scans_create

        create a scan
        """
        pass

    def test_scans_delete(self):
        """
        Test case for scans_delete

        delete a scan
        """
        pass

    def test_scans_list(self):
        """
        Test case for scans_list

        get all scans
        """
        pass

    def test_scans_partial_update(self):
        """
        Test case for scans_partial_update

        update fields on a scan
        """
        pass

    def test_scans_read(self):
        """
        Test case for scans_read

        get a scan
        """
        pass

    def test_scans_update(self):
        """
        Test case for scans_update

        update a scan
        """
        pass

    def test_speedtests_create(self):
        """
        Test case for speedtests_create

        create a speed test
        """
        pass

    def test_speedtests_delete(self):
        """
        Test case for speedtests_delete

        delete a speed test
        """
        pass

    def test_speedtests_list(self):
        """
        Test case for speedtests_list

        list all speed tests
        """
        pass

    def test_speedtests_partial_update(self):
        """
        Test case for speedtests_partial_update

        update fields on a speed test
        """
        pass

    def test_speedtests_read(self):
        """
        Test case for speedtests_read

        get a speed test
        """
        pass

    def test_speedtests_update(self):
        """
        Test case for speedtests_update

        update a speed test
        """
        pass


if __name__ == '__main__':
    unittest.main()
