# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.act_api import ActApi


class TestActApi(unittest.TestCase):
    """ ActApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.act_api.ActApi()

    def tearDown(self):
        pass

    def test_environments_create(self):
        """
        Test case for environments_create

        
        """
        pass

    def test_environments_delete(self):
        """
        Test case for environments_delete

        
        """
        pass

    def test_environments_list(self):
        """
        Test case for environments_list

        
        """
        pass

    def test_environments_partial_update(self):
        """
        Test case for environments_partial_update

        
        """
        pass

    def test_environments_read(self):
        """
        Test case for environments_read

        
        """
        pass

    def test_environments_update(self):
        """
        Test case for environments_update

        
        """
        pass

    def test_intervals_create(self):
        """
        Test case for intervals_create

        create an interval schedule
        """
        pass

    def test_intervals_delete(self):
        """
        Test case for intervals_delete

        delete an interval schedule
        """
        pass

    def test_intervals_list(self):
        """
        Test case for intervals_list

        list interval schedules
        """
        pass

    def test_intervals_partial_update(self):
        """
        Test case for intervals_partial_update

        update fields on an interval schedule
        """
        pass

    def test_intervals_read(self):
        """
        Test case for intervals_read

        get a interval schedule
        """
        pass

    def test_intervals_update(self):
        """
        Test case for intervals_update

        update an interval schedule
        """
        pass

    def test_jobs_create(self):
        """
        Test case for jobs_create

        create a job
        """
        pass

    def test_jobs_delete(self):
        """
        Test case for jobs_delete

        delete a job
        """
        pass

    def test_jobs_list(self):
        """
        Test case for jobs_list

        list all jobs
        """
        pass

    def test_jobs_partial_update(self):
        """
        Test case for jobs_partial_update

        update fields on a job
        """
        pass

    def test_jobs_read(self):
        """
        Test case for jobs_read

        get a job
        """
        pass

    def test_jobs_update(self):
        """
        Test case for jobs_update

        update a job
        """
        pass

    def test_plugins_create(self):
        """
        Test case for plugins_create

        This is the API endpoint for working with Plugins.
        """
        pass

    def test_plugins_delete(self):
        """
        Test case for plugins_delete

        This is the API endpoint for working with Plugins.
        """
        pass

    def test_plugins_list(self):
        """
        Test case for plugins_list

        This is the API endpoint for working with Plugins.
        """
        pass

    def test_plugins_partial_update(self):
        """
        Test case for plugins_partial_update

        This is the API endpoint for working with Plugins.
        """
        pass

    def test_plugins_read(self):
        """
        Test case for plugins_read

        This is the API endpoint for working with Plugins.
        """
        pass

    def test_plugins_update(self):
        """
        Test case for plugins_update

        This is the API endpoint for working with Plugins.
        """
        pass

    def test_results_create(self):
        """
        Test case for results_create

        This is the API endpoint for working with results.
        """
        pass

    def test_results_delete(self):
        """
        Test case for results_delete

        This is the API endpoint for working with results.
        """
        pass

    def test_results_list(self):
        """
        Test case for results_list

        This is the API endpoint for working with results.
        """
        pass

    def test_results_partial_update(self):
        """
        Test case for results_partial_update

        This is the API endpoint for working with results.
        """
        pass

    def test_results_read(self):
        """
        Test case for results_read

        This is the API endpoint for working with results.
        """
        pass

    def test_results_update(self):
        """
        Test case for results_update

        This is the API endpoint for working with results.
        """
        pass

    def test_schedulers_create(self):
        """
        Test case for schedulers_create

        This is the API endpoint for working with Schedulers.
        """
        pass

    def test_schedulers_delete(self):
        """
        Test case for schedulers_delete

        This is the API endpoint for working with Schedulers.
        """
        pass

    def test_schedulers_list(self):
        """
        Test case for schedulers_list

        This is the API endpoint for working with Schedulers.
        """
        pass

    def test_schedulers_partial_update(self):
        """
        Test case for schedulers_partial_update

        This is the API endpoint for working with Schedulers.
        """
        pass

    def test_schedulers_read(self):
        """
        Test case for schedulers_read

        This is the API endpoint for working with Schedulers.
        """
        pass

    def test_schedulers_update(self):
        """
        Test case for schedulers_update

        This is the API endpoint for working with Schedulers.
        """
        pass


if __name__ == '__main__':
    unittest.main()
