# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_31 import Data31


class TestData31(unittest.TestCase):
    """ Data31 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData31(self):
        """
        Test Data31
        """
        model = swagger_client.models.data_31.Data31()


if __name__ == '__main__':
    unittest.main()
