# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_32 import Data32


class TestData32(unittest.TestCase):
    """ Data32 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData32(self):
        """
        Test Data32
        """
        model = swagger_client.models.data_32.Data32()


if __name__ == '__main__':
    unittest.main()
