# coding: utf-8

"""
      Welcome to the interative api documentation   Have a look around...  

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.data_13 import Data13


class TestData13(unittest.TestCase):
    """ Data13 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData13(self):
        """
        Test Data13
        """
        model = swagger_client.models.data_13.Data13()


if __name__ == '__main__':
    unittest.main()
