# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=25)),
                ('firmware', models.CharField(max_length=25)),
                ('ip', models.CharField(max_length=25)),
                ('mfg', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('uniqueid', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_flag', inventory.models.BootFlag()),
                ('ctl_mfg', models.CharField(max_length=25)),
                ('job_name', models.CharField(max_length=25)),
                ('mod_version', models.CharField(max_length=25)),
                ('system_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.System'),
        ),
    ]
