# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='boot_flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
