# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170528_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='boot_flag',
            field=inventory.models.BootFlag(),
        ),
        migrations.AlterField(
            model_name='system',
            name='ctl_mfg',
            field=models.CharField(default='unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='system',
            name='mod_version',
            field=models.CharField(default='unknown', max_length=25),
        ),
    ]
