# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20170608_2108'),
        ('inventory', '0003_auto_20170528_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.Gateway'),
        ),
        migrations.AddField(
            model_name='system',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.Gateway'),
        ),
    ]
