# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('destination', models.CharField(blank=True, max_length=25, null=True)),
                ('ports', models.CharField(blank=True, max_length=25, null=True)),
                ('results', models.TextField(blank=True, max_length=16384, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Scan',
            new_name='Job',
        ),
        migrations.RemoveField(
            model_name='speedtest',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpeedTest',
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discover.Job'),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
