# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_auto_20170524_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeedTestResult',
            new_name='SpeedTest',
        ),
    ]
