# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_host_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='lastboot',
        ),
        migrations.AddField(
            model_name='host',
            name='lastboot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
