# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_bandwidthtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthtestresult',
            name='results',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='results',
            field=models.TextField(blank=True, max_length=512000, null=True),
        ),
    ]
