# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_speedtest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default=b'quick-vendor', max_length=25),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='type',
            field=models.CharField(default=b'speedtest', max_length=25),
        ),
    ]
