# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_auto_20160217_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtestresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 0, 38, 15, 494816, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
