# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_auto_20170526_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedtest',
            name='job',
        ),
    ]
