# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0007_speedtestresult_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='results',
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
    ]
