# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0008_auto_20160217_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtestresult',
            name='destination',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discover.Job'),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='ports',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='destination',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ports',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
