# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 18:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0008_auto_20170526_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='results',
            field=jsonfield.fields.JSONField(blank=True, max_length=512000, null=True),
        ),
    ]
