# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0009_auto_20170526_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'permissions': (('scans', 'View/Perform network scans'),)},
        ),
        migrations.AlterModelOptions(
            name='speedtest',
            options={'permissions': (('speedtests', 'View/Perform Speedtests'),)},
        ),
    ]
