# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20170608_2108'),
        ('discover', '0010_auto_20170611_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='host',
        ),
        migrations.AddField(
            model_name='scan',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.Gateway'),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.Gateway'),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
