# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0012_speedtestresult_job'),
    ]

    operations = [
    ]
