# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discover', '0013_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('ports', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.CharField(default=b'speedtest', max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('results', models.TextField(blank=True, max_length=512000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Job',
            new_name='Scan',
        ),
        migrations.RemoveField(
            model_name='speedtestresult',
            name='job',
        ),
        migrations.RemoveField(
            model_name='speedtestresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpeedTestResult',
        ),
    ]
